### ISSUE TITLE
Animate start point bezier path. #2

### ISSUE THREAD

**Issue by alyfreym** [BlackFoundryCom/bezier-interpolation#2]
hi its possible animate bezier path lines. Like a CAShapeLayer strokenEnd property. I put example image and video what I mean.

I have bezier path
<img width="765" alt="Screenshot 2022-11-20 at 12 37 26" src="https://user-images.githubusercontent.com/29518174/202891996-776f542f-f212-4d27-a7a1-bfcb16ad8b23.png">

Next I have animation with duration 1.0 seconds, when animation started I need calculate bezier points relative animation progress each frame. Below video example.

https://user-images.githubusercontent.com/29518174/202892006-3e602390-c155-4660-bd00-88803221d416.mp4

**Comment by BlackFoundry** [comment]
hello,
I am not sure to understand what you want to achieve?
Do you want to implement that in a variable font?

**Comment by alyfreym** [comment]
> hello,
> I am not sure to understand what you want to achieve?
> Do you want to implement that in a variable font?

I try to implement handwriting text effect. For now I have tools which converts text outlined path to single line path, next i want to animate it. Example image below what I mean by convert outlined glyph to single line 
![Group 3](https://user-images.githubusercontent.com/29518174/202904664-df733632-554d-4bb7-ae49-600f4dc3c51d.png)


if I animate outlined glyph it just follows its contour, but that's not what I need.

**Comment by BlackFoundry** [comment]
in fonts, paths must be closed, and closed paths are filled.

**Comment by alyfreym** [comment]
> in fonts, paths must be closed, and closed paths are filled.

I read about Hershey font and this what I have. but for now I need to animate stroke like video below. 

This is what I DON'T NEED


https://user-images.githubusercontent.com/29518174/202905611-27add437-3e3f-4a91-a8bf-e3132c0d89fa.mp4

This is what I need

https://user-images.githubusercontent.com/29518174/202905656-129df10c-9289-40c7-9d27-1ed910bc55f1.mp4

**Comment by BlackFoundry** [comment]
sorry I don't understand at all :(
what's the relation with this repository ?

**Comment by alyfreym** [comment]
I understand. thank you for your time. I just asking maybe inside your lib have some math function which solve this kind of problem.
